FROM jenkins/ssh-agent:debian-jdk17 as ssh-agent

RUN apt-get update \
  && apt-get install --no-install-recommends -y \
  ca-certificates \
  gnupg \
  curl \
  lsb-release \
  wget \
  && rm -rf /var/lib/apt/lists/*

# install docker
RUN curl -fsSLo /usr/share/keyrings/docker-archive-keyring.asc https://download.docker.com/linux/debian/gpg
RUN echo "deb [arch=$(dpkg --print-architecture) \
  signed-by=/usr/share/keyrings/docker-archive-keyring.asc] \
  https://download.docker.com/linux/debian \
  $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list
RUN apt-get update \
  && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
  docker-ce docker-ce-cli containerd.io && apt-get clean \
  && rm -rf /var/lib/apt/lists/*
# Install Trivvy
RUN wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | apt-key add - && \
  echo deb https://aquasecurity.github.io/trivy-repo/deb bookworm main | tee -a /etc/apt/sources.list.d/trivy.list && \
  apt-get update && apt-get install trivy && apt-get clean